FROM amazoncorretto:22-alpine

WORKDIR /specmatic

ADD https://github.com/znsio/specmatic/releases/download/2.0.37/specmatic.jar /specmatic/specmatic.jar
RUN chmod +x /specmatic/specmatic.jar

WORKDIR /app

ENTRYPOINT ["java", "-jar", "/specmatic/specmatic.jar"]
